version: '3.8'

services:
  fe:
    image: 1-14-fe
    ports:
      - 500:5000

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data

  be:
    image: 1-14-be
    ports:
      - 80:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db
      
  redis:
    image: redis